export const list = [
    {className: 'first', text: 'Smth1'},
    {className: 'second', text: 'Smth2'},
    {className: 'third', text: 'Smth3'},
    {className: 'fourth', text: 'Smth4'},
    {className: 'fifth', text: 'Smth5'},]

export const todoList = [
    {id: '1',
     day: 'Monday',
     todo:{
        wakeup:'done',
         breakfast:'done',
         playingWithCat:'done',
         firstCoding:'done',
         dinner:'done',
         coding:'done',
         lunch:'processed',
         sleep:'processed'},
    image:'https://fydi.ru/wp-content/uploads/2020/09/prikolnye-kartinki-ponedelnik-12.jpg'},
    {id: '2',
        day: 'Tuesday',
        todo:{
            wakeup:'done',
            breakfast:'done',
            playingWithCat:'done',
            firstCoding:'done',
            dinner:'done',
            coding:'done',
            lunch:'processed',
            sleep:'processed'},
    image:'https://funik.ru/wp-content/uploads/2020/12/593f095547580bc2aaa0.jpg'},
    {id: '3',
        day: 'Wednesday',
        todo:{
            wakeup:'done',
            breakfast:'done',
            playingWithCat:'done',
            firstCoding:'done',
            dinner:'done',
            coding:'done',
            lunch:'processed',
            sleep:'processed'},
    image:'https://i09.fotocdn.net/s123/e596ab7f58ed2db7/gallery_xl/2815403988.jpg'},
    {id: '4',
        day: 'Thursday',
        todo:{
            wakeup:'done',
            breakfast:'done',
            playingWithCat:'done',
            firstCoding:'done',
            dinner:'done',
            coding:'done',
            lunch:'processed',
            sleep:'processed'},
        image: 'https://www.sunhome.ru/i/cards/21/skachat-prikolnuyu-otkritku-pro-chetverg.orig.jpg'},
    {id: '5',
        day: 'Friday',
        todo:{
            wakeup:'done',
            breakfast:'done',
            playingWithCat:'done',
            firstCoding:'done',
            dinner:'done',
            coding:'done',
            lunch:'processed',
            sleep:'processed'},
    image: 'https://a.d-cd.net/6a7084cs-960.jpg'},
    {id: '6',
        day: 'Saturday',
        todo:{
            wakeup:'done',
            breakfast:'done',
            playingWithCat:'done',
            firstCoding:'done',
            dinner:'done',
            coding:'done',
            lunch:'processed',
            sleep:'processed'},
    image:'https://i.mycdn.me/i?r=AzEPZsRbOZEKgBhR0XGMT1RkC5mIlmxBcGlDa5d-Rf37w6aKTM5SRkZCeTgDn6uOyic'},
    {id: '7',
        day: 'Sunday',
        todo:{
            wakeup:'done',
            breakfast:'done',
            playingWithCat:'done',
            firstCoding:'done',
            dinner:'done',
            coding:'done',
            lunch:'processed',
            sleep:'processed'},
        image:'https://mirpoprikolu.ru/wp-content/uploads/2020/06/new-1-2.jpg'}]
